### ISSUE TITLE
Embed pdbstr so debugging sdk is no longer required

### ISSUE THREAD

**Issue by GeertvanHorrik** [CatenaLogic/GitLink#40]
Check if we are allowed to distribute the executable.

**Comment by niemyjski** [comment]
+1

**Comment by GeertvanHorrik** [comment]
Someone has access to TFS 2012 so I can get the version I can reproduce?

**Comment by Mpdreamz** [comment]
Installing 2012 update 4 now :sweat_drops: *fingers crossed*

**Comment by Mpdreamz** [comment]
Glad i checked:
The exe file located here:

https://github.com/jstangroome/IndexTeamFoundationSources/tree/e00109aeeb4a73f260ceca77d85d0534d8cbd480/Tools

is version `6.12.2.633` 

Can hold off on installing TFS bloat

**Comment by GeertvanHorrik** [comment]
Cool! I will try to fix this soon (maybe tonight?).

**Comment by Mpdreamz** [comment]
Sweet! can't wait to finally include gitlink in the build for https://github.com/elasticsearch/elasticsearch-net/

**Comment by GeertvanHorrik** [comment]
It's so nice, I can't help but hate products that don't include it. You will get used to it too fast ;-)

**Comment by GeertvanHorrik** [comment]
It's done! See (prerelease) 2.2.0-unstable-2

**Comment by Mpdreamz** [comment]
Awesome @GeertvanHorrik confirm it works, implemented this in our build as per https://github.com/elasticsearch/elasticsearch-net/pull/1188 

Thanks for pursuing this!
